from . import sale_loaned_product
from . import sale_order
from . import sale_order_line
from . import product_template
from . import stock_picking
from . import mail_mail
from . import appointment_type
from . import project_task
from . import project_project
from . import purchase_order
from . import res_users
